name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on:
      - self-hosted
      - zendesk-stable
    steps:
      - name: Checkout
        uses: zendesk/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: zendesk/setup-go@v2
        with:
          go-version: 1.16
      - name: Set ZOAS Build Date
        run: |
          echo "ZOAS_BUILT_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Run GoReleaser
        uses: zendesk/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
