name: ZOAS documentation publish
on:
  repository_dispatch:
    types: publish
  pull_request:
    types: [opened, reopened, synchronize]
env:
  ZOAS_RELEASE_TAG: latest

jobs:
  main:
    name: Publish
    runs-on: [self-hosted,zendesk-stable]
    steps:
      - name: Checkout source
        uses: zendesk/checkout@v2
        with:
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
      - name: Checkout action
        uses: zendesk/checkout@v2
        with:
          repository: zendesk/redback-github-actions
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          path: .github/redback-github-actions
          ref: RED-1170-Add-Postman-In-Github-Action
      - name: Generate documents
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        uses: ./.github/redback-github-actions/actions/zoas-doc-publish
        with:
          documentBaseDir: docs/
          visibility: "\"\""
          mappingPath: .github/workflows/hello.csv

      
